CREATE TABLE tickets_v2(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), display_key TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'ready' CHECK(state IN('draft','ready','in_progress','blocked','review','done')), revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), assigned_agent_id TEXT, summary TEXT NOT NULL DEFAULT '', evidence TEXT NOT NULL DEFAULT '', qa TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id,id), UNIQUE(project_id,display_key), FOREIGN KEY(project_id,assigned_agent_id) REFERENCES agents(project_id,id));
INSERT INTO tickets_v2 SELECT * FROM tickets;
DROP TABLE tickets;
ALTER TABLE tickets_v2 RENAME TO tickets;
CREATE TABLE workflow_policies(project_id TEXT PRIMARY KEY REFERENCES projects(id),revision INTEGER NOT NULL,execution_mode TEXT NOT NULL CHECK(execution_mode IN('human','delegated')),plan_review TEXT NOT NULL CHECK(plan_review IN('lightweight','independent_agent')),validation_mode TEXT NOT NULL CHECK(validation_mode IN('human','independent_agent','automated')),required_checks TEXT NOT NULL DEFAULT '[]',authority TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE workflow_intents(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),kind TEXT NOT NULL,body TEXT NOT NULL,actor_id TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE workflow_ticket_specs(ticket_id TEXT PRIMARY KEY,project_id TEXT NOT NULL,spec_revision INTEGER NOT NULL DEFAULT 1,parent_id TEXT,kind TEXT NOT NULL DEFAULT 'implementation',validation_mode TEXT NOT NULL,required_checks TEXT NOT NULL DEFAULT '[]',policy_revision INTEGER NOT NULL,execution_mode TEXT NOT NULL,plan_review TEXT NOT NULL,prepared_revision INTEGER NOT NULL DEFAULT 0,authorized_revision INTEGER NOT NULL DEFAULT 0,paused INTEGER NOT NULL DEFAULT 0,blocked_reason TEXT NOT NULL DEFAULT '',submitted_commit TEXT NOT NULL DEFAULT '',submitted_spec_revision INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(project_id,ticket_id) REFERENCES tickets(project_id,id),FOREIGN KEY(project_id,parent_id) REFERENCES tickets(project_id,id));
CREATE TABLE workflow_dependencies(project_id TEXT NOT NULL,ticket_id TEXT NOT NULL,depends_on TEXT NOT NULL,PRIMARY KEY(ticket_id,depends_on),FOREIGN KEY(project_id,ticket_id) REFERENCES tickets(project_id,id),FOREIGN KEY(project_id,depends_on) REFERENCES tickets(project_id,id));
CREATE TABLE workflow_versions(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,ticket_id TEXT NOT NULL,spec_revision INTEGER NOT NULL,actor_id TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(ticket_id,spec_revision),FOREIGN KEY(project_id,ticket_id) REFERENCES tickets(project_id,id));
CREATE TABLE workflow_critiques(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,ticket_id TEXT NOT NULL,spec_revision INTEGER NOT NULL,session_id TEXT NOT NULL,agent_id TEXT NOT NULL,context_id TEXT NOT NULL,significant INTEGER NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(project_id,ticket_id) REFERENCES tickets(project_id,id),FOREIGN KEY(project_id,session_id) REFERENCES sessions(project_id,id));
CREATE TABLE workflow_dispositions(critique_id TEXT PRIMARY KEY REFERENCES workflow_critiques(id),actor_id TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE workflow_validations(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,ticket_id TEXT NOT NULL,spec_revision INTEGER NOT NULL,mode TEXT NOT NULL,session_id TEXT,agent_id TEXT,context_id TEXT NOT NULL,commit_id TEXT NOT NULL,criteria TEXT NOT NULL,evidence TEXT NOT NULL,checks TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(project_id,ticket_id) REFERENCES tickets(project_id,id));

